### ISSUE TITLE
Provide necessary information for experimental optimisation

### ISSUE THREAD

**Issue by BenMoon** [CFEL-CMI/pymepix-viewer#4]
Additional to the blob-count, I would like to see some additional numbers and graphs helpful for optimising an experiment optionally displayable in the GUI, e.g.:
- number of ions per time unit as a number and graph, optionally configurable as per shot (trigger) or time-unit (seconds)
- 2D histogram with selectable axis (`tof` vs `tot`, `tot` vs `x`...)
- histogram of `cluster size`, `tot`

**Comment by troehling** [comment]
@BenMoon Can this be closed with the changes I implemented in #7, #8, #9, #12 and #13? Or is there anything that is not covered with the current implementation?

**Comment by BenMoon** [comment]
I think the
- trigger frequency
- open pre-defined folder where data is saved
- (ToT vs x)
are still missing.
